### ISSUE TITLE
the training error

### ISSUE THREAD

**Issue by hanyucool** [hby1320/pytorch_object_detection#1]
model/backbone/resnet50

from torchvision.models.feature_extraction import get_graph_node_names, create_feature_extractor

This line of code keeps reporting errors.What is the reason?

**Comment by hby1320** [comment]
Please tell me which version of pytorch and torchvison you are using.

**Comment by hanyucool** [comment]
pytorch: 1.8.0   +cuda11.1

**Comment by hby1320** [comment]
This function is supported since pytorch 1.10.
(TorchVision 0.11 to be exact)
Maybe installing the latest pytorch will solve it.
